### ISSUE TITLE
Lehrer fehlt

### ISSUE THREAD

**Issue by Locus43** [marvinborner/Abizeugs#6]
Lehrer Honold fehlt im Lehrerranking

**Comment by marvinborner** [comment]
Möglich. Anscheinend fehlen mehrere Lehrer; die stehen halt nicht auf der Lehrerliste..

**Comment by marvinborner** [comment]
Ggf. könntest du eine komplette Lehrerliste organisieren?

**Comment by Locus43** [comment]
kann ich machen, ja

**Comment by LarsVomMars** [comment]
Wir haben mittlerweile eine Lehrerliste, sollte bald gefixt sein.

**Comment by marvinborner** [comment]
Not so fast @LarsVomMars :)
Would you mind sending me a txt with all the teacher names instead (I don't like xlsx, yk)?

**Comment by LarsVomMars** [comment]
Later
