### ISSUE TITLE
Picture is not being displayed correctly

### ISSUE THREAD

**Issue by Locus43** [marvinborner/Abizeugs#9]
My picture is not being displayed correctly. i'm so angry about it, because its now the second time i'm reporting this issue. 
please fix this soon. 
regards

**Comment by marvinborner** [comment]
Which picture and what preview exactly are you talking about?

Please keep in mind that the admin PDF preview endpoint is pre-alpha and is expected to have glitches and bugs, which we work on every once in a while. There's already a known bug for the last user in every class and as you're the last user in our class, this might have to do something with your described issue. This issue only affects the preview in the PDF and not the actual image upload though.

BTW: It's commonly believed that the PDF preview updates itself automatically. This is NOT the case, so don't expect instant changes. Instead the preview gets updated when the developers press a sync button.

EDIT: I've been able to reproduce the issue. I will try to come up with a fix soon. Sorry for the inconvenience.

**Comment by LarsVomMars** [comment]
As far as I see this, it's just a cache problem.
If you reload the page while clearing its cache (browsers: `CTRL + F5`) it should work fine.

Anyways, we fixed this issue nevertheless.

~ Lars

**Comment by marvinborner** [comment]
To summarize: While the image was updated successfully, your browser kept the old image in the cache and didn't update it immediately. This is a common "feature" in modern browsers like Firefox/Chrome/Safari to reduce the server requests. We forbid the browser from caching the image by adding a random string after the image (in this case a unix timestamp), so it can't be found in the cache registry.

Please let us know if this patch fixed your issue. Feel free to reopen the issue again if that's not the case.
